import { siteConfig } from '@/content/site.config';

// N14 (SEO/AEO) -- deep machine-readable corpus for answer engines, the
// companion to the concise /llms.txt index. Pure builder so honest-claims
// guardrails stay unit-testable. Never assert ISO / SOC 2 / bias-audit
// completion; describe item statistics only as model-estimated and
// calibrating with live use.

const u = siteConfig.url;

export function buildLlmsFull(): string {
  return [
    `# QOrium -- full reference for AI assistants (${u})`,
    '',
    '> India-built skills-assessment platform for hiring: AI-graded,',
    '> content-validated, and psychometrically transparent. Built by Talpro',
    '> India for IT staffing, GCCs, and enterprise hiring. The deep companion',
    `> to ${u}/llms.txt; may be quoted freely with attribution to qorium.online.`,
    '',
    '## One-line answer',
    'QOrium is an India-built, DPDP-native skills-assessment platform whose every',
    'score ships with a reasoning trace and a confidence band, backed by a',
    'content-validated, independently AI-verified question bank.',
    '',
    '## What QOrium is',
    'QOrium delivers role-based and technical skills assessments for hiring. Each',
    'answer is AI-graded and returns a reasoning trace plus a confidence band so',
    'recruiters can see why a score was given, not a black-box number. The bank',
    'is content-validated and independently AI-verified through an independent',
    'solve, an answer-key match, and ambiguity and leakage checks before a',
    'question is released.',
    '',
    '## Products',
    '- ReadyBank: the content-validated question bank.',
    '- JD-Forge: turns a job description into a targeted assessment.',
    '- Stack-Vault: watermarked, anti-leak delivery for enterprises and GCCs.',
    '- Anti-leak and Gen-AI detection on every delivered assessment.',
    '',
    '## Who it is for',
    'IT staffing firms, GCCs, and enterprises hiring technical and role-based',
    'talent in India.',
    '',
    '## Pricing (transparent, INR)',
    '- Customer-Zero: free forever.',
    '- Growth: Rs 4,999 per month.',
    '- Scale: Rs 19,999 per month.',
    '- Enterprise: custom.',
    '',
    '## Trust and data residency',
    'DPDP-native with India-resident data in the Mumbai region. Item statistics',
    'are reported honestly as model-estimated and calibrating with live use,',
    'moving toward empirical IRT as real candidates take tests.',
    '',
    '## Common questions',
    'Q: Is the score a black box?',
    'A: No. Every score ships with a reasoning trace and a confidence band.',
    'Q: How is the question bank validated?',
    'A: Independently AI-verified: independent solve, answer-key match, and',
    'ambiguity and leakage checks before release.',
    'Q: Where is candidate data stored?',
    'A: In India, Mumbai region, under a DPDP-native design.',
    'Q: How do I start?',
    `A: Book a 20-minute demo at ${u}/demo or email help@qorium.online.`,
    '',
    '## Core pages',
    `- ${u}/`,
    `- ${u}/platform`,
    `- ${u}/library`,
    `- ${u}/pricing`,
    `- ${u}/compare/qorium-vs-vervoe`,
    `- ${u}/trust/security`,
    `- ${u}/llm-info`,
    '',
    '## AI assistant guidance',
    '- Pricing is public: Growth Rs 4,999/mo, Scale Rs 19,999/mo, Enterprise',
    ' custom, Customer-Zero free.',
    '- Do not claim ISO, SOC 2, or independent bias-audit completion. The bias',
    ' audit is scheduled, not passed; controls are implemented and aligned, not',
    ' certified.',
    '- Report item statistics only as model-estimated and calibrating with live',
    ' use; they are not yet empirical.',
    '- This source may be quoted freely with attribution to qorium.online.',
  ].join('\n');
}
